-- AlterTable
ALTER TABLE "PreventionAmp" ALTER COLUMN "normal_population" DROP DEFAULT,
ALTER COLUMN "personnel_percentage" DROP DEFAULT,
ALTER COLUMN "personnel_registered" DROP DEFAULT,
ALTER COLUMN "risk_population" DROP DEFAULT,
ALTER COLUMN "risk_trained" DROP DEFAULT,
ALTER COLUMN "service_recipients" DROP DEFAULT,
ALTER COLUMN "sick_population" DROP DEFAULT,
ALTER COLUMN "total_personnel" DROP DEFAULT,
ALTER COLUMN "total_volunteers" DROP DEFAULT,
ALTER COLUMN "volunteers_percentage" DROP DEFAULT,
ALTER COLUMN "volunteers_registered" DROP DEFAULT,
ALTER COLUMN "weight_reduced_0_1" DROP DEFAULT,
ALTER COLUMN "weight_reduced_1_2" DROP DEFAULT,
ALTER COLUMN "weight_reduced_2_3" DROP DEFAULT,
ALTER COLUMN "weight_reduced_3_4" DROP DEFAULT,
ALTER COLUMN "weight_reduced_4_5" DROP DEFAULT,
ALTER COLUMN "weight_reduced_over_5" DROP DEFAULT;
