import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StagewiseToolbar } from "@stagewise/toolbar-next";
import ReactPlugin from "@stagewise-plugins/react";
import Sidebar from "../components/Sidebar";
import { AuthProvider } from "../contexts/AuthContext";
import VisitCounter from "../components/VisitCounter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NCDs Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <VisitCounter />
          
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 bg-gray-50">
              {children}
            </main>
          </div>
          {process.env.NODE_ENV === 'development' && (
            <StagewiseToolbar config={{
              plugins: [ReactPlugin],
            }} />
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
